### ISSUE TITLE
Code Block Overflow in Chat UI Due to Unwrapped Preformatted Text

### ISSUE THREAD

**Issue by joesoc** [joesoc/knowledge-discovery-ui#2]
### 🔍 **CSS Issue Description:**

1. **Horizontal Overflow (Text Clipping)**  
   - The code block (`pre` or `code` element) is wider than its container, causing the horizontal scroll bar to appear or text to overflow beyond the visible area.
   - This happens because long lines of code (like `SecurityInfoKeys=123456789,...`) are not wrapping or being truncated gracefully.

2. **Lack of Horizontal Scrolling or Wrapping (UX Problem)**
   - The code content doesn't wrap or scroll within the visible boundaries of the message container.
   - This might confuse users or make it difficult to read the full configuration without manual effort.

3. **Container or Font Styling**
   - The font may not be using a proper monospace font for code blocks, reducing readability.
   - It appears the code block is not padded sufficiently from the edges, which affects legibility.

---

### ✅ **Suggested CSS Fixes:**

You can fix this by adding styles like:

```css
pre, code {
  white-space: pre-wrap; /* or pre-line if you want line breaks */
  word-wrap: break-word;
  overflow-x: auto;
  font-family: monospace;
  padding: 8px;
  background-color: #f4f4f4; /* Optional: Better visibility */
  border-radius: 4px;         /* Optional: Aesthetics */
}
```

Alternatively, if you want **scrolling instead of wrapping**:

```css
pre {
  overflow-x: auto;
  white-space: pre;
}
```
